import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cash App",
  description: "Generated by Vinnie",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning={true} data-lt-installed="true">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
